### ISSUE TITLE
Integer ID's?

### ISSUE THREAD

**Issue by Longor1996** [martin-t/cvars#8]
Would it be possible to have a pair of `set_var` and `get_var`-functions that use an integer-index (parallel to `str`), obtainable by some `get_idx` function? Maybe also have a macro that can resolve this at compile-time?

This could be implemented by wrapping the memory-offset (using https://crates.io/crates/memoffset ?) in a `CvarHandle<T> {offset: u16}` struct with an `impl PartialEq`, where `T` is the source-type... thus never exposing the actual offset to the library user.

**Comment by martin-t** [comment]
Yes, I've been thinking about using offsets for some time. It should reduce compile times because there would be less generated code - #6 . I won't have time in the next two weeks, hopefully after that - i wanna do this before integrating cvars into rustcycles because i don't wanna add several seconds to its compile time. I didn't plan on exposing the offsets/handles to users but i don't see why not either.

Do you have a specific usecase or just think it would be a good idea?

**Comment by martin-t** [comment]
I thought about this and the compile times are probably OK-ish (cvars add 400 ms IIRC). I also don't really have time to do more optimizations, i'd rather focus on my games because cvars are at this point good-enough.

I don't see much benefit for supporting integer IDs fro ma user's perspective. If you have a usecase, let me know but i think you can always just have a (bidirectional) hashmap between cvar names and IDs if you really need numbers for something.

Adding a way to get a list of cvars is on my todo list and then pushing those into a hashmap will be trivial.

Closing for now.
